### ISSUE TITLE
Org files not detected automatically

### ISSUE THREAD

**Issue by bodograumann** [axvr/org.vim#6]
It seems files ending with `.org` are not automatically detected as `filetype=org`.
Only after I manually call `set ft=org` does the org.vim plugin syntax highlighting take effect.

vim version:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 27 2021 23:06:36)
Included patches: 1-2815
Compiled by Arch Linux

**Comment by axvr** [comment]
Hi @bodograumann, this can happen if your `.vimrc` doesn’t contain
```vim
set filetype plugin indent on
```

If that doesn’t fix it could you share your `.vimrc` file (or just the relevant parts) so I try to find what is causing the issue.

**Comment by bodograumann** [comment]
Ok, I found it. The problem occurs, when I also have vim-polyglot installed :thinking:

**Comment by axvr** [comment]
I don’t use Vim-Polyglot so I can’t really help, but maybe you could try adding this to your `.vimrc`:

```vim
let g:polyglot_disabled = ['org']
```

If you find a solution please let me know, so I can mention it in the README.
